'use strict'
import './modules/swiper.js';
import './modules/range.js';
import './modules/yandex_map.js';
import './modules/limitStr.js';
import './modules/birthPicker.js';
import './modules/cartAddCount.js';
import './modules/cartCountBtn.js';
import './modules/openSearchFilter.js';
import './modules/infoTabs.js';
import './modules/filter.js'
import './modules/searchResultMore.js';
import './modules/filterObserver.js';
import './modules/showMorePlaces.js';
import './modules/reviewStarControl.js';
import './modules/addReview.js';
import './modules/copyToClipboard.js';
import './modules/custom_select.js';
import './modules/profilePageTogglers.js';
import './modules/filterModalFields.js';
import './modules/modalState.js'
import './modules/main-tabs.js';
import './modules/compareTabs.js';
import './modules/loginModal.js';
import './modules/mobile-menu.js';
